### ISSUE TITLE
Any guidance on systemd?

### ISSUE THREAD

**Issue by stacecom** [jarshwah/slack-regex-responder#1]
The upstart scripts are appreciated, but I'm trying to get this running in a systemd environment and not having much luck.

**Comment by stacecom** [comment]
I was able to get it to start with the following (though it's not logging except to systemctl status)

```
[Unit]
Description=Slack Autoresponder
After=network.target

[Service]
Environment=LC_ALL=en_AU.UTF-8
Environment=LANG=en_AU.UTF-8
ExecStart=/usr/local/bin/slack_responder /etc/slack_responder/foo.yaml
Restart=on-failure
RestartSec=15
StartLimitInterval=60s
StartLimitBurst=3

[Install]
WantedBy=multi-user.target
```

**Comment by jarshwah** [comment]
@stacecom sorry I don't remember seeing any notification for this issue. Thanks for showing what worked for you. With regards to logging, everything should be logged to the journal and then to syslog and /var/log/messages depending on your OS.

You might also want this line in your systemd script too if each log message is prefixed with `python` rather than `slackresponder`, but I haven't checked specifically:

```
SyslogIdentifier=slackresponder
```
